apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: LoadBalancer
  selector:
    app: gateway-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: registry.localhost:5001/gateway-svc:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: CONFIG_URI
          value: http://configuration-svc:8080
        - name: SERVICE_REGISTRY_URI
          value: http://service-registry-svc:8761
        - name: NON_SECURE_PORT_ENABLED
          value: "true"    
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTLP_URI
          value: http://otel-collector:4317