server:
  ssl:
    enabled: true
    certificate: classpath:cert/localhost.com.crt
    certificate-private-key: classpath:cert/localhost.com.key
    trust-store: classpath:cert/truststore.jks
    trust-store-password: changeit
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:https://localhost:8443}/realms/${KEYCLOAK_REALM:AaapliSociety}  
eureka:
  client:
    healthcheck: 
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URI:https://localhost:8761}/eureka/
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
logging:
  level:
    root: WARN
    com.gm: DEBUG        