spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URI:https://localhost:8443}/realms/${KEYCLOAK_REALM:AaapliSociety}
            user-name-attribute: preferred_username
        registration:
          api-gateway-svc:
            provider: keycloak
            client-id: gateway-service
            client-secret: yIfxP6oV8SQNYaLpFPtYDb0AFtgkPh5G
            scope:
            - email
            - profile          
      resourceserver:
        opaquetoken:
          introspection-uri: ${KEYCLOAK_URI:https://localhost:8443}/realms/${KEYCLOAK_REALM:AaapliSociety}/protocol/openid-connect/token/introspect 
          client-id: gateway-service
          client-secret: yIfxP6oV8SQNYaLpFPtYDb0AFtgkPh5G
        jwt:
          issuer-uri: ${KEYCLOAK_URI:https://localhost:8443}/realms/${KEYCLOAK_REALM:AaapliSociety}
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      default-filters:
      - TokenRelay
      - name: CircuitBreaker
        args:
          fallbackUri: forward:/fallback
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: gateway, health, info, prometheus
logging:
  level:
    org.springframework.security: DEBUG
    reactor.netty: INFO
    org.springframework.cloud.gateway: TRACE