apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: app-cluster
servers: 1
agents: 2
kubeAPI:
  host: "app-cluster.localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
network: apps-bridge-netwrk
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5001"
  config: |
    mirrors:
      "registry":
        endpoint:
          - http://registry:5000