
version: '3.8'
services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    ports:
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=Welcome@MinIo
    networks:
      - services-tier
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
      - GF_LOG_LEVEL=warn
    restart: unless-stopped
    volumes:
      - ${HOME}/docker-mount/grafana:/var/lib/grafana
      - ./tempo/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - services-tier
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo-s3.yaml:/etc/tempo.yaml
      - ${HOME}/docker-mount/tempo-data:/tmp/tempo
    ports:
      - "3200:3200"  # tempo
      - "4317"
      - "4318"
    restart: on-failure
    depends_on:
      - minio
    networks:
      - services-tier
  otel-collector:
    image: otel/opentelemetry-collector:0.80.0
    container_name: otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    restart: unless-stopped
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    networks:
      - services-tier
networks:
  services-tier:
    driver: bridge


