{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Start time of the application process",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time{job=\"$application\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Duration of the application process is running",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{job=~\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "description": "Usable space for path where application process is running",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free{job=\"$application\"}"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "stat",
   "description": "The open file descriptor count",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_files_open{job=\"$application\"}"
    }
   ]
  },
  {
   "title": "Max GC Pause",
   "type": "stat",
   "description": "Max Time spent in GC pause",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_gc_pause_max{job=\"$application\"})"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free{job=\"$application\"}"
    }
   ]
  },
  {
   "title": "CPU Usages",
   "type": "gauge",
   "description": "Process CPU Usages",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"$application\"} * 1"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "description": "Heap memory used by application",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used{job=\"$application\", area=\"heap\"}) * 100) / sum(jvm_memory_max{job=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non Heap Used",
   "type": "gauge",
   "description": "Non Heap memory used by process",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(jvm_memory_used{job=\"$application\", area=\"nonheap\"}) * 100) / sum(jvm_memory_max{job=\"$application\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (disk_free{job=\"$application\"} / disk_total{job=\"$application\"}*100)"
    }
   ]
  },
  { "title": "I/O Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$application\"}",
     "legendFormat": "System"
    },
    {
     "expr": "process_cpu_usage{job=\"$application\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"$application\"}[15m])",
     "legendFormat": "Process - 15m"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$application\"}",
     "legendFormat": "system-load-1m"
    },
    {
     "expr": "system_cpu_count{job=\"$application\"}",
     "legendFormat": "cpus"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "http_server_requests_count{job=\"$application\", uri!~\"/*/*\", status=~\"5..|4..\"}",
     "legendFormat": "{{uri}} - {{status}}"
    }
   ]
  },
  { "title": "JVM Stats - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_runtime_jvm_memory_usage{job=\"$application\", type=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_committed{job=\"$application\", type=\"heap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(process_runtime_jvm_memory_limit{job=\"$application\", type=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used{job=\"$application\", area=\"nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed{job=\"$application\", area=\"nonheap\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max{job=\"$application\", area=\"nonheap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used{job=\"$application\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed{job=\"$application\"})",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(jvm_memory_max{job=\"$application\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{job=\"$application\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": "delta(jvm_classes_loaded{job=\"$application\"}[1m])",
     "legendFormat": "Delta-1m"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_live{job=\"$application\"} - jvm_threads_daemon{job=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon{job=\"$application\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Threads States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_states{job=\"$application\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(jvm_gc_pause_sum{job=\"$application\"}[1m])) / on(job) system_cpu_count",
     "legendFormat": "CPU Time Spent on GC"
    }
   ]
  },
  {
   "title": "Pause Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_sum{job=\"$application\"}[1m])/rate(jvm_gc_pause_sum{job=\"$application\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocation/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated{job=\"$application\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted{job=\"$application\"}[1m])"
    }
   ]
  }
 ]
}