receivers:
  otlp:
    protocols:
      grpc: 
      http:

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
    
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: otel-collector:8889
  # Send OpenTelemetry metrics to Prometheus remote write compatiable backends
  # such as Cortex, Mimir
  prometheusremotewrite:
    endpoint: http://load-balancer:9009/api/v1/push
    tls:
      insecure: true

processors:
  batch:

service:
  extensions: []
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus, prometheusremotewrite, logging]