apiVersion: v1
kind: Service
metadata:
  name: service-registry-svc
  labels:
    app: service-registry-svc
spec:
  selector:
    app: service-registry-svc
  ports:
    - port: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-svc
  labels:
    app: service-registry-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry-svc
  template:
    metadata:
      labels:
        app: service-registry-svc
    spec:
      containers:
      - name: service-registry-svc
        image: registry.localhost:5000/service-registry-svc:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8761
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
        env:
        - name: CONFIG_URI
          value: http://configuration-svc:8080