apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: service-registry-svc
build:
  insecureRegistries:
    - registry.localhost:5001
  artifacts:
    - image: service-registry-jib
      jib: {}
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - k8s/*