spring:
  application:
    name: greet-svc
  config:
    import: 'configserver:' 
  cloud:
    config:
      fail-fast: true
      profile: local
      uri: ${CONFIG_URI:http://localhost:7575}
      username: ${CONFIG_USER:config-svc}
      password: ${CONFIG_USER_PHRASE:Config!12}
logging:
  level:
    org.springframework.cloud.config: DEBUG