spring:
  application:
    name: greet-svc
  profiles:
    active: local
  config:
    import: 'configserver:' 
  cloud:
    config:
      uri: ${CONFIG_URI:https://localhost:7575}
      username: ${CONFIG_USER:user}
      password: ${CONFIG_USER_PHRASE:Config!12}      