spring:
  application:
    name: greet-svc
  profiles:
    active: local
  config:
    import: 'configserver:' 
  cloud:
    config:
      uri: ${CONFIG_URI:https://localhost:7575}
      username: ${CONFIG_USR:user}
      password: ${CONFIG_PHRASE:Config!12}
      fail-fast: true
      retry:
        max-attempts: 5
        max-interval: 15000
        initial-interval: 10000