spring:
  application:
    name: service-registry-svc
  config:
    import: 'configserver:' 
  cloud:
    config:
      profile: local 
      uri: ${CONFIG_URI:http://localhost:7575}
      username: ${CONFIG_USER:config-svc}
      password: ${CONFIG_USER_PHRASE:Config!12}
      tls:
        enabled: true
        key-store: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
        key-store-password: ${KEYSTORE_PHRASE:localhost}
        key-password: ${KEYSTORE_KEY_PHRASE:localhost}
        trust-store: ${TRUSTSTORE_PATH:classpath:cert/truststore.jks}
        trust-store-password: ${TRUSTSTORE_PHRASE:localhost}