server:
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
    key-alias: ${KEYSTORE_ALIAS:localhost}
    key-store-password: ${KEYSTORE_PHRASE:localhost}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-password: ${KEYSTORE_KEY_PHRASE:localhost}
    trust-store: ${TRUSTSTORE_PATH:classpath:cert/truststore.jks}
    trust-store-password: ${TRUSTSTORE_PHRASE:localhost}
encrypt:
  keyStore:
    location: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
    password: ${KEYSTORE_PHRASE:localhost}
    alias: configserverkey
    secret: ${CONFIG_ENCRYPTION_PHRASE:localhost}    
spring:
  application:
    name: configserver-svc
  profiles:
    active: composite
  security:
    user:
      name: ${CONFIG_USR_NAME:config-svc}
      password: ${CONFIG_USR_PHRASE:Config!12}
    actuator-user:
      name: ${ACTUATOR_USR_NAME:actuator}
      password: ${ACTUATOR_USR_PHRASE:Actuator!12}
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: 
            - file://${HOME}/application/config
            - classpath:config-{profile}
            - classpath:config-{label}
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
logging:
  level:
    root: WARN
    com.gm: DEBUG