server:
  port: 7575
  ssl:
    enabled: true
    key-store: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
    key-alias: ${KEYSTORE_ALIAS:localhost}
    key-store-password: ${KEYSTORE_PHRASE:localhost}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-password: ${KEYSTORE_KEY_PHRASE:localhost}
    trust-store: ${TRUST_STORE_PATH:classpath:cert/truststore.jks}
    trust-store-password: ${TRUSTSTORE_PHRASE:localhost}
spring:
  profiles:
    active: composite
  security:
    user:
      name: ${CONFIG_USER:user}
      password: ${CONFIG_USER_PHRASE:Config!12}
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: 
            - file://${HOME}/application/config
            - classpath:config-{profile}
            - classpath:config-{label}
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
logging:
  config: 'classpath:logback-spring.xml'
  level:
    root: WARN
    com.gm: DEBUG