server:
  port: 7575
  ssl:
    enabled: true
    key-store: classpath:cert/keystore.p12
    key-alias: ${KEYSTORE_ALIAS:localhost}
    key-store-password: ${KEYSTORE_PHRASE:localhost}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-password: ${KEYSTORE_KEY_PHRASE:localhost}
    trust-store: classpath:cert/truststore.jks
    trust-store-password: ${TRUSTSTORE_PHRASE:localhost}
encrypt:
  keyStore:
    location: classpath:cert/keystore.p12
    password: ${KEYSTORE_PHRASE:localhost}
    alias: configserverkey
    secret: ${CONFIG_ENCRYPTION_PHRASE:localhost}    
spring:
  application:
    name: configserver-svc
  profiles:
    active: composite
  security:
    user:
      name: config-svc
      password: Config!12
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: 
            - file://${HOME}/application/config
            - classpath:config-{profile}
            - classpath:config-{label}         
logging:
  level:
    root: WARN
    com.gm: DEBUG