server:
  port: 7575
spring:
  application:
    name: configserver-svc
  profiles:
    active: composite
  security:
    user:
      name: ${CONFIG_USR_NAME:config-svc}
      password: ${CONFIG_USR_PHRASE:Config!12}
    actuator-user:
      name: ${ACTUATOR_USR_NAME:actuator}
      password: ${ACTUATOR_USR_PHRASE:Actuator!12}
  cloud:
    config:
      server:
        composite:
          - type: native
            search-locations: 
            - file://${HOME}/application/config
            - classpath:config-{profile}
            - classpath:config-{label}
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
logging:
  level:
    root: WARN
    com.gm: DEBUG