server:
  ssl:
    enabled: true
    key-store: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
    key-alias: ${KEYSTORE_ALIAS:localhost}
    key-store-password: ${KEYSTORE_PHRASE:localhost}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-password: ${KEYSTORE_KEY_PHRASE:localhost}
    trust-store: ${TRUSTSTORE_PATH:classpath:cert/truststore.jks}
    trust-store-password: ${TRUSTSTORE_PHRASE:localhost}
eureka:
  instance:
    hostname: ${SERVICE_INSTANCE_HOST:localhost}
    preferIpAddress: ${SERVICE_INSTANCE_PREFER_IP:false}
    secure-port-enabled: ${server.ssl.enabled:false}
    secure-port: ${server.port:8080}
    non-secure-port-enabled: ${NON_SECURE_PORT_ENABLED:false}
  client:
    webclient:
      enabled: true
    region: default
    registryFetchIntervalSeconds: 5
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    healthcheck: 
      enabled: ${EUREKA_HEALTH_CHECK_ENABLED:true}
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URI:https://localhost:8761}/eureka
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
spring:
  main:
    banner-mode: off
logging:
  pattern:
    # Include trace Id and Span Id into logs
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: WARN
    com.gm: DEBUG