server:
  ssl:
    enabled: true
    key-store: ${KEYSTORE_PATH:classpath:cert/keystore.p12}
    key-alias: ${KEYSTORE_ALIAS:localhost}
    key-store-password: ${KEYSTORE_PHRASE:localhost}
    key-store-type: ${KEYSTORE_TYPE:PKCS12}
    key-password: ${KEYSTORE_KEY_PHRASE:localhost}
    trust-store: ${TRUST_STORE_PATH:classpath:cert/truststore.jks}
    trust-store-password: ${TRUSTSTORE_PHRASE:localhost}
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
    preferIpAddress: ${EUREKA_USE_IP:false}
    secure-port-enabled: true
    secure-port: ${server.port:8080}
    non-secure-port-enabled: false
  client:
    healthcheck: 
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URI:https://localhost:8761}/eureka/
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
logging:
  level:
    root: WARN
    com.gm: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:https://localhost:8443}/realms/${KEYCLOAK_REALM}              