server:
eureka:
  instance:
    hostname: ${SERVICE_INSTANCE_HOST:localhost}
    preferIpAddress: ${SERVICE_INSTANCE_PREFER_IP:false}
    secure-port-enabled: ${server.ssl.enabled:false}
    secure-port: ${server.port:8080}
    non-secure-port-enabled: ${NON_SECURE_PORT_ENABLED:true}
  client:
    webclient:
      enabled: true
    region: default
    registryFetchIntervalSeconds: 5
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    health-check:
      enabled: ${EUREKA_HEALTH_CHECK_ENABLED:true}
    registerWithEureka: ${REGISTER_WITH_EUREKA:true}
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URI:http://localhost:8761}/eureka
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - prometheus
        - metrics
spring:
  main:
    banner-mode: off
logging:
  level:
    root: WARN
    com.gm: DEBUG