spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
management:
  otlp:
    tracing:
      sampling:
        # Sample all of the requests instead of default 10%
        probability: 1.0f 
    metrics:
      export:
        enabled: false
        step: 1m
        url: http://localhost:4318/v1/metrics         
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
logging:  
  level:
    org.springframework.security: WARN
    reactor.netty: WARN
    org.springframework.cloud.gateway: WARN