spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
management:
  endpoint:
    gateway:
      enabled: true
logging:
  level:
    org.springframework.security: WARN
    reactor.netty: WARN
    org.springframework.cloud.gateway: WARN