spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info, prometheus
logging:
  level:
    org.springframework.security: DEBUG
    reactor.netty: WARN
    org.springframework.cloud.gateway: TRACE