apiVersion: v1
kind: Service
metadata:
  name: configuration-svc
  labels:
    app: configuration-svc
spec:
  selector:
    app: configuration-svc
  ports:
  - port: 8080
    targetPort: 7575
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-svc
  labels:
    app: configuration-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-svc
  template:
    metadata:
      labels:
        app: configuration-svc
    spec:
      containers:
      - name: configuration-svc
        image: registry.localhost:5001/configuration-svc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7575
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 7575
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 7575
          initialDelaySeconds: 5
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 7575
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
